---
trigger:
  - master
jobs:
  - job: "Test"
    pool:
      vmImage: "ubuntu-latest"
    strategy:
      matrix:
        precommit:
          python.version: "3.8"
          tox.env: precommit
        flake8:
          python.version: "3.8"
          tox.env: flake8
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: Install Python.
      - script: pip install --upgrade tox
        displayName: Install Tox.
      - script: tox -e $(tox.env)
        displayName: Run Tox.
